#pragma once

/* From glfw3.h */

#define HAZEL_MOUSE_BUTTON_1         0
#define HAZEL_MOUSE_BUTTON_2         1
#define HAZEL_MOUSE_BUTTON_3         2
#define HAZEL_MOUSE_BUTTON_4         3
#define HAZEL_MOUSE_BUTTON_5         4
#define HAZEL_MOUSE_BUTTON_6         5
#define HAZEL_MOUSE_BUTTON_7         6
#define HAZEL_MOUSE_BUTTON_8         7
#define HAZEL_MOUSE_BUTTON_LAST      HAZEL_MOUSE_BUTTON_8
#define HAZEL_MOUSE_BUTTON_LEFT      HAZEL_MOUSE_BUTTON_1
#define HAZEL_MOUSE_BUTTON_RIGHT     HAZEL_MOUSE_BUTTON_2
#define HAZEL_MOUSE_BUTTON_MIDDLE    HAZEL_MOUSE_BUTTON_3
